name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Installer les dependances
        run: npm install
      - name: Creer le .env
        run: echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
      - name: Builder l app
        run: npm run build
      - name: Pousser le build sur branche dist
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dist
          publish_dir: ./dist
